idf_component_register(
  SRCS
  "main.cpp"
  "gps/gpsUsbHost.cpp"
  "sensors/gpsSensor.cpp"
  "algo/gpsGoalAlgo.cpp"
  "manager/MasterManager.cpp"
  "manager/AdvancedFusionEngine.cpp"
  "manager/CoupeCircuitManager.cpp"
  "wifi_control_server.cpp"
  "lidarReader.cpp"
  "drive.cpp"
  "algo/LidarObstacleAvoidance/lidar_obstacle_avoidance_algorithm.cpp"
  "gpsdrive.cpp"
  "vescController.cpp"
  "vesc/PhysicalVescController.cpp"
  "vescLidarUart.c"
  "rmt-uart/rmt_uart.c"

  PRIV_REQUIRES
  driver
  esp_wifi
  bt
  esp_netif
  esp_event
  nvs_flash
  lwip
  esp_http_server
  usb
  esp_driver_uart
  esp_driver_gpio

  INCLUDE_DIRS
  "."
  "manager"
  "gps"
  "rmt-uart"
)
